name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "Running resize script"
    - run: sudo add-apt-repository ppa:strukturag/libheif
    - run: sudo apt-get install libheif-examples
    - run: sudo apt-get update
    - run: heif-convert IMG_0910.HEIC IMG_0910.HEIC.jpg
    - uses: actions/upload-artifact@v2
      with:
        name: IMG_0910.HEIC
        path: IMG_0910.HEIC.jpg